title: MACSio
email: gonsie@llnl.gov
description: A Multi-purpose, Application-Centric, Scalable I/O Proxy Application
baseurl: "/MACSio"
url: ""
github_username: markmiller86

# vars used by Jekyll-LLNL-Theme
name: MACSio
githubrepo: MACSio

# Build settings
markdown: kramdown

# Gem theme
#theme: jekyll-llnl-theme

# Gem theme through gh-pages
remote_theme: gonsie/Jekyll-LLNL-Theme

plugins_dir:
  - jekyll-feed
